import type { Metadata } from "next";
import Tabs from "./components/Tabs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main>
      <Tabs />
      {children}
    </main>
  );
}
